#file: noinspection SpellCheckingInspection
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: databases
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  orders:
    build:
      context: .
      dockerfile: CommonDockerfile
    container_name: orders
    entrypoint: ["go", "run", "order/cmd/main.go"]
    depends_on:
      - db

volumes:
  db-data: